### ISSUE TITLE
How to fillout the .env file?

### ISSUE THREAD

**Issue by rookiecooder28** [sehyunkwon/ICTC#1]
Could u please give us detailed information on running ur code? i.e., how to configure .env file?
I'm writing this because I followed ur README, and failed to run ur code.

**Comment by jadenpark0** [comment]
You need API access to the GPTs or Llamas. If you do not have access to these, you would need to access the LLMs differently, for example through HuggingFace. (You would need to change the caller functions accordingly, too).

**Comment by rookiecooder28** [comment]
您好！您发来的邮件我已收到，将会尽快处理。祝您生活愉快，工作顺利！谭雨泽Tel：18981770691

**Comment by rookiecooder28** [comment]
> You need API access to the GPTs or Llamas. If you do not have access to these, you would need to access the LLMs differently, for example through HuggingFace. (You would need to change the caller functions accordingly, too).

Appreciate it! But now I come across "NotImplementedError", which looks like this:
`(ictc) tyz@scdx:~/ICTC$ python step1/blip2/model.py --dataset cifar10
Python-dotenv could not parse statement starting at line 1
[2023-11-21 13:36:11,601] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Python-dotenv could not parse statement starting at line 1
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:35<00:00,  5.98s/it]
Traceback (most recent call last):
  File "/home/tyz/ICTC/step1/blip2/model.py", line 81, in <module>
    eval_model(args)
  File "/home/tyz/ICTC/step1/blip2/model.py", line 55, in eval_model
    model, processor = load_model()
  File "/home/tyz/ICTC/step1/blip2/model.py", line 30, in load_model
    model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xxl", device_map="auto", torch_dtype=torch.float16).cuda()
  File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))

NotImplementedError: Cannot copy out of meta tensor; no data!
`
I followed every step of README and changed the HOME_PATH accordingly. I suppose there's nothing wrong with environment settings. I'm wondering if u had been the same sittuation before and how did you solve it? Thanks a lot!

**Comment by rookiecooder28** [comment]
> > You need API access to the GPTs or Llamas. If you do not have access to these, you would need to access the LLMs differently, for example through HuggingFace. (You would need to change the caller functions accordingly, too).
> 
> Appreciate it! But now I come across "NotImplementedError", which looks like this: `(ictc) tyz@scdx:~/ICTC$ python step1/blip2/model.py --dataset cifar10 Python-dotenv could not parse statement starting at line 1 [2023-11-21 13:36:11,601] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect) Python-dotenv could not parse statement starting at line 1 Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:35<00:00, 5.98s/it] Traceback (most recent call last): File "/home/tyz/ICTC/step1/blip2/model.py", line 81, in eval_model(args) File "/home/tyz/ICTC/step1/blip2/model.py", line 55, in eval_model model, processor = load_model() File "/home/tyz/ICTC/step1/blip2/model.py", line 30, in load_model model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xxl", device_map="auto", torch_dtype=torch.float16).cuda() File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda return self._apply(lambda t: t.cuda(device)) File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply module._apply(fn) File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply module._apply(fn) File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply module._apply(fn) [Previous line repeated 5 more times] File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply param_applied = fn(param) File "/home/tyz/anaconda3/envs/ictc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in return self._apply(lambda t: t.cuda(device))
> 
> NotImplementedError: Cannot copy out of meta tensor; no data! ` I followed every step of README and changed the HOME_PATH accordingly. I suppose there's nothing wrong with environment settings. I'm wondering if u had been in the same situation before and how did you solve it? Thanks a lot!

Btw, I've downloaded cifar10 properly.

**Comment by sehyunkwon** [comment]
Sorry for being late. Is the issue still unresolved?

**Comment by rookiecooder28** [comment]
您好！您发来的邮件我已收到，将会尽快处理。祝您生活愉快，工作顺利！谭雨泽Tel：18981770691
